# Generated by Django 5.2.10 on 2026-01-29 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20, unique=True)),
                ('setor', models.CharField(blank=True, max_length=50, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estagio', models.CharField(choices=[('INICIO', 'Início'), ('MENU_PRINCIPAL', 'Menu Principal'), ('AGUARDANDO_DETALHES', 'Aguardando Detalhes'), ('AGUARDANDO_ATENDENTE', 'Aguardando Atendente'), ('FINALIZADO', 'Finalizado')], default='INICIO', max_length=50)),
                ('setor_escolhido', models.CharField(blank=True, max_length=50, null=True)),
                ('protocolo', models.CharField(blank=True, max_length=50, null=True)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.colaborador')),
            ],
        ),
    ]
